// Code generated by protoc-gen-go. DO NOT EDIT.
// source: object.proto

package objectpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Object struct {
	Value1               string   `protobuf:"bytes,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               int32    `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{0}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetValue1() string {
	if m != nil {
		return m.Value1
	}
	return ""
}

func (m *Object) GetValue2() int32 {
	if m != nil {
		return m.Value2
	}
	return 0
}

func init() {
	proto.RegisterType((*Object)(nil), "beamexample.Object")
}

func init() {
	proto.RegisterFile("object.proto", fileDescriptor_41d48463eef19a5f)
}

var fileDescriptor_41d48463eef19a5f = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4a, 0x4d, 0xcc, 0x4d, 0xad,
	0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55, 0xb2, 0xe0, 0x62, 0xf3, 0x07, 0x4b, 0x0a, 0x89, 0x71, 0xb1,
	0x95, 0x25, 0xe6, 0x94, 0xa6, 0x1a, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x70,
	0x71, 0x23, 0x09, 0x26, 0xa0, 0x38, 0x2b, 0x54, 0xdc, 0xc8, 0x49, 0x3f, 0x4a, 0x37, 0x3d, 0xb3,
	0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x3d, 0x3f, 0xaf, 0x2a, 0x3f, 0x2b, 0xb3,
	0x2c, 0x55, 0x1f, 0x64, 0xba, 0x6e, 0x7a, 0xbe, 0x2e, 0xd4, 0x06, 0x7d, 0x88, 0xdd, 0x05, 0x49,
	0x49, 0x6c, 0x60, 0xeb, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xee, 0x30, 0x50, 0x9c, 0x8e,
	0x00, 0x00, 0x00,
}
